# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 951fcbfe8f03cb59e9e359dd48a95ea11580057e5561be9b29e60aa7cfece9a04a9bd1d1ef4b3a66e8c3dc8fd5d9a6f8a66615f8ecd430fd7ffd1a0503fe1bea

test:
  secret_key_base: 1f07f863ae143d936a0681f09675fb46dbf7724dd99d8acd20ebd936945c4f47986a0dcb407d75a43e3efb06ac565de94309b5d57ebc83bd57177bc7bb4ea6ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
